sheenisms = [
"""I have a disease? Bullshit. I cured it with my brain.""",
"""Winning, anyone? Rhymes with winning. Anyone? Yeah, that would be us. Sorry, man, didn't make the rules. Oops!""",
"""I'm tired of pretending I'm not a total bitchin' rock star from Mars.""",
"""You can't process me with a normal brain.""",
"""If you borrowed my brain for five seconds, you'd be like, "Dude! Can't handle it, unplug this bastard!" It fires in a way that's maybe not from, uh... this terrestrial realm.""",
"""I was banging seven-gram rocks, because that's how I roll.  I have one speed, I have one gear: Go.""",
"""Can't is the cancer of happening.""",
"""Wow.  What does that mean? I'm bi-WINNING.""",
"""I am battle-tested bayonets, bro.""",
"""I'm so tired of pretending my life isn't perfect and bitching and just winning every second and I'm not perfect and bitchin'.""",
"""Look what I'm dealing with, man, I'm dealing with fools and trolls.""",
"""It's just strafing runs in my underwear before my first cup of coffee, because I don't have time for these clowns.""",
"""You have the right to kill me, but you do not have the right to judge me. Boom. That's the whole movie. That's life.""",
"""I'm sorry man, I got magic and I've got poetry in my fingertips, you know, most of the time, and this includes naps.""",
"""I'm an F-18, bro.""",
"""I'm not Thomas Jefferson. He was a pussy.""",
"""I am on a drug, it's called Charlie Sheen. It's not available because if you try it you will die. Your face will melt off and your children will weep over your exploded body.""",
"""I'm bi-winning.""",
"""There's a new sheriff in town. And he has an army of assassins.""",
"""The run I was on made Sinatra, Flynn, Jagger, Richards, all of them look like droopy-eyed armless children.""",
"""The only thing I'm addicted to right now is winning.""",
"""I wish him nothing but pain in his silly travels especially if they wind up in my octagon. Clearly I have defeated this earthworm with my words -- imagine what I would have done with my fire breathing fists.""",
"""[CBS] picked a fight with a warlock.""",
"""If you're a part of my family, I will love you violently.""",
"""Winning.""",
"""I will not believe that if I do something then I have to follow a certain path because it was written for normal people. People who aren't special. People who don't have tiger blood and Adonis DNA.""",
"""C'mon bro, I won best picture at 20. I wasn't even trying. I wasn't even warm.""",
"""There's been a tsunami of media, and I've been riding it on a mercury surfboard.""",
"""I have a 10,000 year old brain and the boogers of a seven-year old.""",
"""Bring me Dr. Clown shoes.""",
"""I'm shakin' a tree.  I'm shakin' all the trees. """,
"""I'm grandiose.  Because I live a grandiose life.  I'm not aw shucks... because I'm gnarly.""",
"""I'm celebrating me, every day.""",
"""I live inside the truth, and you cannot debate me.""",
"""Panic is for amateurs and morons.""",
"""I think I'm worth over a 100 BILLION dollars, but that's just on a cellular level.""",
"""I'm sober down to my Adonis DNA.""",
"""And for those that are not onboard, it's like, 'Catch ya in the rearview, losers.'""",
]
